name: dnscrypt
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master
    paths:
      - dnscrypt/**
      - .github/workflows/dnscrypt.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Build
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            zydou/${{ github.workflow }}:${{ env.date }}
            zydou/${{ github.workflow }}:latest
            ghcr.io/zydou/${{ github.workflow }}:${{ env.date }}
            ghcr.io/zydou/${{ github.workflow }}:latest
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/dnscrypt
          short-description: "Dockerized dnscrypt client based on alpine"
          readme-filepath: ${{ github.workflow }}/README.md
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ${{ github.workflow }}
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}

  adblock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build adblock
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/adblock.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            zydou/${{ github.workflow }}:adblock
            zydou/${{ github.workflow }}:adblock-${{ env.date }}
            ghcr.io/zydou/${{ github.workflow }}:adblock
            ghcr.io/zydou/${{ github.workflow }}:adblock-${{ env.date }}
      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ${{ github.workflow }}
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}

  cnlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Build cnlist
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/cnlist.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            zydou/${{ github.workflow }}:cnlist-${{ env.date }}
            zydou/${{ github.workflow }}:cnlist
            ghcr.io/zydou/${{ github.workflow }}:cnlist-${{ env.date }}
            ghcr.io/zydou/${{ github.workflow }}:cnlist

      - name: Delete untagged
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ${{ github.workflow }}
          token: ${{ secrets.PAT }}
          user: ${{ github.repository_owner }}