name: naiveproxy
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master
    paths:
      - naiveproxy/**
      - .github/workflows/naiveproxy.yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: x86, platform: linux/386}
          - {arch: x86_64, platform: linux/amd64}
          - {arch: aarch64_cortex-a53-static, platform: linux/arm64}
          - {arch: aarch64_cortex-a53, platform: linux/arm64}
          - {arch: aarch64_cortex-a72-static, platform: linux/arm64}
          - {arch: aarch64_cortex-a72, platform: linux/arm64}
          - {arch: aarch64_cortex-a76, platform: linux/arm64}
          - {arch: aarch64_generic-static, platform: linux/arm64}
          - {arch: aarch64_generic, platform: linux/arm64}
          - {arch: arm_arm1176jzf-s_vfp, platform: linux/arm/v6}
          - {arch: arm_cortex-a15_neon-vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a5_vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a7, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_neon-vfpv4-static, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_neon-vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_vfpv4, platform: linux/arm/v7}
          - {arch: arm_arm926ej-s, platform: linux/arm}
          - {arch: arm_cortex-a8_vfpv3, platform: linux/arm}
          - {arch: arm_cortex-a9-static, platform: linux/arm}
          - {arch: arm_cortex-a9, platform: linux/arm}
          - {arch: arm_cortex-a9_neon, platform: linux/arm}
          - {arch: arm_cortex-a9_vfpv3-d16, platform: linux/arm}
          - {arch: arm_mpcore, platform: linux/arm}
          - {arch: arm_xscale, platform: linux/arm}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get latest release
        id: latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: klzgrad/naiveproxy
        run:
          echo "TAG=$(gh api /repos/${{env.REPO}}/releases/latest --jq .tag_name)" >> $GITHUB_OUTPUT

      - name: Print release version
        run: |
          echo "${{ steps.latest-release.outputs.TAG }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
          VERSION: ${{ steps.latest-release.outputs.TAG }}
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=${{ matrix.arch }}
          tags: |
            ghcr.io/zydou/${{ github.workflow }}:${{ env.VERSION }}-${{ matrix.arch }}
            ghcr.io/zydou/${{ github.workflow }}:${{ matrix.arch }}
            zydou/${{ github.workflow }}:${{ env.VERSION }}-${{ matrix.arch }}
            zydou/${{ github.workflow }}:${{ matrix.arch }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ github.workflow }}
          short-description: "Minimal naiveproxy client. (only 5MB)"
          readme-filepath: ${{ github.workflow }}/README.md

  build-multi:
    runs-on: ubuntu-latest
    needs: ["build"]
    strategy:
      fail-fast: false
      matrix:
        include:
          - {arch: x86, platform: linux/386}
          - {arch: x86_64, platform: linux/amd64}
          - {arch: aarch64_cortex-a53-static, platform: linux/arm64}
          - {arch: aarch64_cortex-a53, platform: linux/arm64}
          - {arch: aarch64_cortex-a72-static, platform: linux/arm64}
          - {arch: aarch64_cortex-a72, platform: linux/arm64}
          - {arch: aarch64_cortex-a76, platform: linux/arm64}
          - {arch: aarch64_generic-static, platform: linux/arm64}
          - {arch: aarch64_generic, platform: linux/arm64}
          - {arch: arm_arm1176jzf-s_vfp, platform: linux/arm/v6}
          - {arch: arm_cortex-a15_neon-vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a5_vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a7, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_neon-vfpv4-static, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_neon-vfpv4, platform: linux/arm/v7}
          - {arch: arm_cortex-a7_vfpv4, platform: linux/arm/v7}
          - {arch: arm_arm926ej-s, platform: linux/arm}
          - {arch: arm_cortex-a8_vfpv3, platform: linux/arm}
          - {arch: arm_cortex-a9-static, platform: linux/arm}
          - {arch: arm_cortex-a9, platform: linux/arm}
          - {arch: arm_cortex-a9_neon, platform: linux/arm}
          - {arch: arm_cortex-a9_vfpv3-d16, platform: linux/arm}
          - {arch: arm_mpcore, platform: linux/arm}
          - {arch: arm_xscale, platform: linux/arm}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Get latest release
        id: latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: klzgrad/naiveproxy
        run:
          echo "TAG=$(gh api /repos/${{env.REPO}}/releases/latest --jq .tag_name)" >> $GITHUB_OUTPUT
      - name: Print release version
        run: |
          echo "${{ steps.latest-release.outputs.TAG }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v3
        env:
          CONTEXT: ${{ github.workflow }}
          VERSION: ${{ steps.latest-release.outputs.TAG }}
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/multi.Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          build-args: |
            VERSION=${{ env.VERSION }}
            ARCH=${{ matrix.arch }}
          tags: |
            ghcr.io/zydou/${{ github.workflow }}:multi-${{ env.VERSION }}-${{ matrix.arch }}
            ghcr.io/zydou/${{ github.workflow }}:multi-${{ matrix.arch }}
            zydou/${{ github.workflow }}:multi-${{ env.VERSION }}-${{ matrix.arch }}
            zydou/${{ github.workflow }}:multi-${{ matrix.arch }}
