name: v2ray
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master
    paths:
      - v2ray/**
      - .github/workflows/v2ray.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@master
        env:
          CONTEXT: ${{ github.workflow }}
          VERSION: "v4.45.2"
        with:
          context: ./${{ env.CONTEXT}}
          file: ./${{ env.CONTEXT }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          build-args: VERSION=${{ env.VERSION }}
          tags: |
            zydou/${{ github.workflow }}:latest
            zydou/${{ github.workflow }}:${{ env.VERSION }}
            zydou/${{ github.workflow }}:${{ env.DATE }}
            ghcr.io/zydou/${{ github.workflow }}:latest
            ghcr.io/zydou/${{ github.workflow }}:${{ env.VERSION }}
            ghcr.io/zydou/${{ github.workflow }}:${{ env.DATE }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ github.workflow }}
          short-description: "V2Ray 路由规则文件加强版，代替 V2Ray 官方 geoip.dat 和 geosite.dat"
          readme-filepath: ${{ github.workflow }}/README.md