name: v2ray
env:
  VERSION: v4.45.2
on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  push:
    branches:
      - master
    paths:
      - v2ray/**
      - .github/workflows/v2ray.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@master
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@master
        with:
          input_string: ${{ env.VERSION }}
          version_extractor_regex: 'v(.*)$'

      - name: Build (pinned latest to v4)
        if: steps.semver_parser.outputs.major == 4
        uses: docker/build-push-action@master
        with:
          context: ./${{ github.workflow }}
          file: ./${{ github.workflow }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          build-args: VERSION=${{ env.VERSION }}
          tags: |
            zydou/${{ github.workflow }}:latest
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            zydou/${{ github.workflow }}:nightly-${{ env.DATE }}
            ghcr.io/zydou/${{ github.workflow }}:latest
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            ghcr.io/zydou/${{ github.workflow }}:nightly-${{ env.DATE }}

      - name: Build
        if: steps.semver_parser.outputs.major != 4
        uses: docker/build-push-action@master
        with:
          context: ./${{ github.workflow }}
          file: ./${{ github.workflow }}/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6,linux/386
          push: ${{ github.event_name != 'pull_request' }}
          build-args: VERSION=${{ env.VERSION }}
          tags: |
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            zydou/${{ github.workflow }}:nightly-${{ env.DATE }}
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ghcr.io/zydou/${{ github.workflow }}:v${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
            ghcr.io/zydou/${{ github.workflow }}:nightly-${{ env.DATE }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@main
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }}
          repository: ${{ github.repository_owner }}/${{ github.workflow }}
          short-description: "V2Ray 路由规则文件加强版，代替 V2Ray 官方 geoip.dat 和 geosite.dat"
          readme-filepath: ${{ github.workflow }}/README.md